"""phase 10 readme promos

Revision ID: 1e938c9563fd
Revises: 054433adad83
Create Date: 2026-09-18 21:06:48.022526

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '1e938c9563fd'
down_revision = '054433adad83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readme_promos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_kind', sa.String(length=16), nullable=False),
    sa.Column('readme_sha256', sa.String(length=64), nullable=False),
    sa.Column('readme_chars', sa.Integer(), nullable=False),
    sa.Column('sent_chars', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.Text(), nullable=False),
    sa.Column('one_liner', sa.Text(), nullable=False),
    sa.Column('cover_text', sa.Text(), nullable=False),
    sa.Column('versions', sa.JSON(), nullable=False),
    sa.Column('source_points', sa.JSON(), nullable=False),
    sa.Column('unknowns', sa.JSON(), nullable=False),
    sa.Column('image_ideas', sa.JSON(), nullable=False),
    sa.Column('digest', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readme_promos_readme_sha256'), 'readme_promos', ['readme_sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_readme_promos_readme_sha256'), table_name='readme_promos')
    op.drop_table('readme_promos')
    # ### end Alembic commands ###
