"""phase 13 knowledge articles and tags

Revision ID: 39476a18a4e2
Revises: 71ffdbefb778
Create Date: 2026-09-19 07:06:03.170492

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '39476a18a4e2'
down_revision = '71ffdbefb778'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('blurb', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_tags_name'), 'knowledge_tags', ['name'], unique=True)
    op.create_table('knowledge_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('hook', sa.Text(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('glossary', sa.JSON(), nullable=False),
    sa.Column('further_reading', sa.JSON(), nullable=False),
    sa.Column('audience', sa.String(length=64), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('takeaways', sa.JSON(), nullable=False),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cny', sa.Float(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['knowledge_tags.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_articles_created_at'), 'knowledge_articles', ['created_at'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_tag_id'), 'knowledge_articles', ['tag_id'], unique=False)
    op.create_index(op.f('ix_knowledge_articles_topic'), 'knowledge_articles', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_articles_topic'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_tag_id'), table_name='knowledge_articles')
    op.drop_index(op.f('ix_knowledge_articles_created_at'), table_name='knowledge_articles')
    op.drop_table('knowledge_articles')
    op.drop_index(op.f('ix_knowledge_tags_name'), table_name='knowledge_tags')
    op.drop_table('knowledge_tags')
    # ### end Alembic commands ###
