"""section 16: detail provenance columns

Revision ID: 09191b9cb921
Revises: 9bc56092f38a
Create Date: 2026-09-18 17:25:53.312536

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '09191b9cb921'
down_revision = '9bc56092f38a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hot_contents', sa.Column('detail_fetched_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('hot_contents', sa.Column('detail_endpoint', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hot_contents', 'detail_endpoint')
    op.drop_column('hot_contents', 'detail_fetched_at')
    # ### end Alembic commands ###
