"""phase 4: ai_rewrites

Revision ID: ce1202df003e
Revises: c11d0cc7eda0
Create Date: 2026-09-18 17:01:34.208610

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'ce1202df003e'
down_revision = 'c11d0cc7eda0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_rewrites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hot_content_id', sa.Integer(), nullable=False),
    sa.Column('topic_group_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('why_hot', sa.Text(), nullable=False),
    sa.Column('angle', sa.Text(), nullable=False),
    sa.Column('xiaohongshu_title', sa.Text(), nullable=False),
    sa.Column('xiaohongshu_content', sa.Text(), nullable=False),
    sa.Column('xiaohongshu_ending', sa.Text(), nullable=False),
    sa.Column('xiaohongshu_hashtags', sa.JSON(), nullable=False),
    sa.Column('weibo_opening', sa.Text(), nullable=False),
    sa.Column('weibo_title', sa.Text(), nullable=False),
    sa.Column('weibo_content', sa.Text(), nullable=False),
    sa.Column('weibo_hashtags', sa.JSON(), nullable=False),
    sa.Column('douyin_hook', sa.Text(), nullable=False),
    sa.Column('douyin_script', sa.Text(), nullable=False),
    sa.Column('douyin_scene_suggestions', sa.JSON(), nullable=False),
    sa.Column('douyin_subtitles', sa.Text(), nullable=False),
    sa.Column('douyin_cta', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('risk_flags', sa.JSON(), nullable=False),
    sa.Column('needs_verification', sa.Boolean(), nullable=False),
    sa.Column('verification_note', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('copy_similarity', sa.Float(), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hot_content_id'], ['hot_contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_group_id'], ['topic_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_rewrites_created', 'ai_rewrites', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_rewrites_hot_content_id'), 'ai_rewrites', ['hot_content_id'], unique=True)
    op.create_index('ix_ai_rewrites_status', 'ai_rewrites', ['status'], unique=False)
    op.create_index(op.f('ix_ai_rewrites_topic_group_id'), 'ai_rewrites', ['topic_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_rewrites_topic_group_id'), table_name='ai_rewrites')
    op.drop_index('ix_ai_rewrites_status', table_name='ai_rewrites')
    op.drop_index(op.f('ix_ai_rewrites_hot_content_id'), table_name='ai_rewrites')
    op.drop_index('ix_ai_rewrites_created', table_name='ai_rewrites')
    op.drop_table('ai_rewrites')
    # ### end Alembic commands ###
