"""phase 2: hot_contents and topic_groups

Revision ID: 0a35efd10ab8
Revises: 
Create Date: 2026-09-18 16:45:50.734171

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0a35efd10ab8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('topic_normalized', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_topic_groups_created', 'topic_groups', ['created_at'], unique=False)
    op.create_index('ix_topic_groups_normalized', 'topic_groups', ['topic_normalized'], unique=False)
    op.create_table('hot_contents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('platform_content_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('author_id', sa.String(length=128), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('publish_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('hot_value', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('collects', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=16), nullable=False),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('title_normalized', sa.String(length=512), nullable=False),
    sa.Column('url_normalized', sa.String(length=1024), nullable=True),
    sa.Column('topic_group_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['topic_group_id'], ['topic_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'platform_content_id', name='uq_hot_contents_platform_content')
    )
    op.create_index('ix_hot_contents_created', 'hot_contents', ['created_at'], unique=False)
    op.create_index('ix_hot_contents_platform_rank', 'hot_contents', ['platform', 'rank'], unique=False)
    op.create_index('ix_hot_contents_title_norm', 'hot_contents', ['title_normalized'], unique=False)
    op.create_index(op.f('ix_hot_contents_topic_group_id'), 'hot_contents', ['topic_group_id'], unique=False)
    op.create_index('ix_hot_contents_url_norm', 'hot_contents', ['url_normalized'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_hot_contents_url_norm', table_name='hot_contents')
    op.drop_index(op.f('ix_hot_contents_topic_group_id'), table_name='hot_contents')
    op.drop_index('ix_hot_contents_title_norm', table_name='hot_contents')
    op.drop_index('ix_hot_contents_platform_rank', table_name='hot_contents')
    op.drop_index('ix_hot_contents_created', table_name='hot_contents')
    op.drop_table('hot_contents')
    op.drop_index('ix_topic_groups_normalized', table_name='topic_groups')
    op.drop_index('ix_topic_groups_created', table_name='topic_groups')
    op.drop_table('topic_groups')
    # ### end Alembic commands ###
