"""phase 11 image generations

Revision ID: 71ffdbefb778
Revises: 0724f967b8c7
Create Date: 2026-09-18 23:33:53.301577

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '71ffdbefb778'
down_revision = '0724f967b8c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_generations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hot_content_id', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('reference_paths', sa.JSON(), nullable=False),
    sa.Column('result_urls', sa.JSON(), nullable=False),
    sa.Column('local_paths', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('size', sa.String(length=32), nullable=False),
    sa.Column('requested_n', sa.Integer(), nullable=False),
    sa.Column('usage', sa.JSON(), nullable=False),
    sa.Column('estimated_usd', sa.Float(), nullable=False),
    sa.Column('estimated_cny', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hot_content_id'], ['hot_contents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_generations_hot_content_id'), 'image_generations', ['hot_content_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_generations_hot_content_id'), table_name='image_generations')
    op.drop_table('image_generations')
    # ### end Alembic commands ###
