"""phase 3: ai_analyses

Revision ID: c11d0cc7eda0
Revises: 0a35efd10ab8
Create Date: 2026-09-18 16:53:26.165215

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'c11d0cc7eda0'
down_revision = '0a35efd10ab8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hot_content_id', sa.Integer(), nullable=False),
    sa.Column('topic_group_id', sa.Integer(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('why_hot', sa.Text(), nullable=False),
    sa.Column('content_angle', sa.Text(), nullable=False),
    sa.Column('discussion_points', sa.JSON(), nullable=False),
    sa.Column('account_fit', sa.Text(), nullable=False),
    sa.Column('recommended', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('needs_verification', sa.Boolean(), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hot_content_id'], ['hot_contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_group_id'], ['topic_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_analyses_created', 'ai_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_analyses_hot_content_id'), 'ai_analyses', ['hot_content_id'], unique=True)
    op.create_index('ix_ai_analyses_recommended', 'ai_analyses', ['recommended', 'confidence'], unique=False)
    op.create_index(op.f('ix_ai_analyses_topic_group_id'), 'ai_analyses', ['topic_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_analyses_topic_group_id'), table_name='ai_analyses')
    op.drop_index('ix_ai_analyses_recommended', table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_hot_content_id'), table_name='ai_analyses')
    op.drop_index('ix_ai_analyses_created', table_name='ai_analyses')
    op.drop_table('ai_analyses')
    # ### end Alembic commands ###
